### PR TITLE
Fix Circle config to use Ruby 3.1

### PR DESCRIPTION
**Pull request by seven1m**

### CODE REVIEW

**Review by tannermares — APPROVED** [review]
Simple enough! What do you think about switching this our use our circleci-tools orb?
```
version: '2.1'
orbs:
  rails: planningcenter/rails@2.2.0
jobs:
  build:
    executor:
      name: rails/minimal
      ruby-version: '3.1'
    steps:
      - checkout
      - rails/bundle
      - rails/test:
          test-runner: rspec
workflows:
  commit:
    jobs:
      - test:
          context:
            - GitHub Packages
            - AWS ECR (circleci-tools)
  version: 2
```

https://circleci.com/developer/orbs/orb/planningcenter/rails

see `simple-gem-setup`

**Comment by seven1m** [comment]
Huh, [that didn't work](https://app.circleci.com/pipelines/github/planningcenter/pco_api_ruby/29). Is there a benefit to using the shared orb given this is such a simple build?

**Review by kevinthompson — APPROVED** [review]

**Comment by tannermares** [comment]
@seven1m not really... just that you would be using the same tooling we're using everywhere else.

**Comment by seven1m** [comment]
Sorry I gave up 😩

**Pull request merged**
